services:
  PrestaShop\Module\KeycloakConnectorDemo\Form\ConfigurationType:
    class: PrestaShop\Module\KeycloakConnectorDemo\Form\ConfigurationType
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  prestashop.module.keycloak_connector_demo.php_encrypt:
    class: PhpEncryption
    arguments:
      - !php/const _NEW_COOKIE_KEY_

  prestashop.module.keycloak_connector_demo.client:
    class: GuzzleHttp\Client

  PrestaShop\Module\KeycloakConnectorDemo\RequestBuilder:
    class: PrestaShop\Module\KeycloakConnectorDemo\RequestBuilder
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.module.keycloak_connector_demo.php_encrypt'

  PrestaShop\Module\KeycloakConnectorDemo\Form\ConfigurationDataConfiguration:
    class: PrestaShop\Module\KeycloakConnectorDemo\Form\ConfigurationDataConfiguration
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.module.keycloak_connector_demo.php_encrypt'
      - '@PrestaShop\Module\KeycloakConnectorDemo\RequestBuilder'
      - '@prestashop.module.keycloak_connector_demo.client'

  PrestaShop\Module\KeycloakConnectorDemo\Form\ConfigurationDataProvider:
    class: PrestaShop\Module\KeycloakConnectorDemo\Form\ConfigurationDataProvider
    arguments:
      - '@PrestaShop\Module\KeycloakConnectorDemo\Form\ConfigurationDataConfiguration'

  prestashop.module.keycloak_connector_demo.form.configuration_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    public: true
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@PrestaShop\Module\KeycloakConnectorDemo\Form\ConfigurationDataProvider'
      - 'PrestaShop\Module\KeycloakConnectorDemo\Form\ConfigurationType'
      - 'KeycloakConfiguration'

  PrestaShop\Module\KeycloakConnectorDemo\Controller\ConfigurationController:
    autowire: true
    autoconfigure: true

  PrestaShop\Module\KeycloakConnectorDemo\OAuth2\KeycloakAuthorizationServer:
    # Autoconfigure to get tag from interface and to be injected in TokenAuthenticator
    autoconfigure: true
    autowire: true
    arguments:
      $client: '@prestashop.module.keycloak_connector_demo.client'
      $phpEncryption: '@prestashop.module.keycloak_connector_demo.php_encrypt'
